kind: pipeline
type: docker
name: Docker Build

trigger:
  event:
  - cron
  cron:
  - weekly

steps:
- name: DockerHub  
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: dockerhub_pw
    repo: fuzzymistborn/docker-linting
    tags: latest

- name: GH Container Registry  
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: ghcr_pw
    repo: ghcr.io/fuzzymistborn/docker-linting
    registry: ghcr.io
    tags: latest

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: >
      {{#success build.status}}
      ✅  Build for `{{repo.name}}` was *successful*!

      🌐  [Output]({{build.link}})
      {{else}}
      ❌  Build for `{{repo.name}}` has *FAILED*!

      🌐  [Output]({{build.link}})
      {{/success}}
  when:
    status: [ success, failure ]
