kind: pipeline
type: docker
name: Docker Build

trigger:
  branch:
  - dev

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

steps:
- name: Build and push release
  image: fuzzymistborn/docker-alpine-skopeo:latest
  environment:
    DOCKERHUB_PASS:
      from_secret: dockerhub_pw
    GHCR_PASS:
      from_secret: ghcr_pw
    PYTHON_VER: python-3.8
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker login docker.io -u fuzzymistborn -p $DOCKERHUB_PASS
    - docker login ghcr.io -u fuzzymistborn -p $GHCR_PASS
    - docker build -t fuzzymistborn/docker-linting:dev -t ghcr.io/fuzzymistborn/docker-linting:dev .
    - docker push fuzzymistborn/docker-linting:dev
    - docker push ghcr.io/fuzzymistborn/docker-linting:dev

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: "{{#success build.status}}✅  Dev Build for `{{repo.name}}` was *successful*!{{else}}❌  Dev Build for `{{repo.name}}` has *FAILED*!{{/success}} \n🌐  [Output]({{build.link}})\n📝  Commit: {{ commit.message }}"
  when:
    status: [ success, failure ]
