kind: pipeline
type: docker
name: Docker Build

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: dockerhub_pw
    repo: fuzzymistborn/docker-linting
    tags: latest
