kind: pipeline
type: docker
name: Docker Build

steps:
- name: DockerHub  
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: dockerhub_pw
    repo: fuzzymistborn/docker-linting
    tags: latest

- name: GH Container Registry  
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: ghcr_pw
    repo: fuzzymistborn/docker-linting
    registry: ghcr.io
    tags: latest
